<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsersPasswd', 'doctrine');

/**
 * BaseUsersPasswd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property integer $gid
 * @property string $username
 * @property string $info
 * @property string $password
 * @property UsersGroup $UsersGroup
 * @property Doctrine_Collection $UsersGroups
 * @property Doctrine_Collection $UsersPermissions
 * 
 * @method integer             getUid()              Returns the current record's "uid" value
 * @method integer             getGid()              Returns the current record's "gid" value
 * @method string              getUsername()         Returns the current record's "username" value
 * @method string              getInfo()             Returns the current record's "info" value
 * @method string              getPassword()         Returns the current record's "password" value
 * @method UsersGroup          getUsersGroup()       Returns the current record's "UsersGroup" value
 * @method Doctrine_Collection getUsersGroups()      Returns the current record's "UsersGroups" collection
 * @method Doctrine_Collection getUsersPermissions() Returns the current record's "UsersPermissions" collection
 * @method UsersPasswd         setUid()              Sets the current record's "uid" value
 * @method UsersPasswd         setGid()              Sets the current record's "gid" value
 * @method UsersPasswd         setUsername()         Sets the current record's "username" value
 * @method UsersPasswd         setInfo()             Sets the current record's "info" value
 * @method UsersPasswd         setPassword()         Sets the current record's "password" value
 * @method UsersPasswd         setUsersGroup()       Sets the current record's "UsersGroup" value
 * @method UsersPasswd         setUsersGroups()      Sets the current record's "UsersGroups" collection
 * @method UsersPasswd         setUsersPermissions() Sets the current record's "UsersPermissions" collection
 * 
 * @package    gui
 * @subpackage model
 * @author     Artem Yankovskiy <admin@neverdark.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsersPasswd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_passwd');
        $this->hasColumn('uid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('gid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('info', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UsersGroup', array(
             'local' => 'gid',
             'foreign' => 'gid'));

        $this->hasMany('UsersGroups', array(
             'local' => 'uid',
             'foreign' => 'uid'));

        $this->hasMany('UsersPermissions', array(
             'local' => 'uid',
             'foreign' => 'uid'));
    }
}