<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsersGroup', 'doctrine');

/**
 * BaseUsersGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $gid
 * @property string $groupname
 * @property string $info
 * @property Doctrine_Collection $UsersGroups
 * @property Doctrine_Collection $UsersPasswd
 * @property Doctrine_Collection $UsersPermissions
 * 
 * @method integer             getGid()              Returns the current record's "gid" value
 * @method string              getGroupname()        Returns the current record's "groupname" value
 * @method string              getInfo()             Returns the current record's "info" value
 * @method Doctrine_Collection getUsersGroups()      Returns the current record's "UsersGroups" collection
 * @method Doctrine_Collection getUsersPasswd()      Returns the current record's "UsersPasswd" collection
 * @method Doctrine_Collection getUsersPermissions() Returns the current record's "UsersPermissions" collection
 * @method UsersGroup          setGid()              Sets the current record's "gid" value
 * @method UsersGroup          setGroupname()        Sets the current record's "groupname" value
 * @method UsersGroup          setInfo()             Sets the current record's "info" value
 * @method UsersGroup          setUsersGroups()      Sets the current record's "UsersGroups" collection
 * @method UsersGroup          setUsersPasswd()      Sets the current record's "UsersPasswd" collection
 * @method UsersGroup          setUsersPermissions() Sets the current record's "UsersPermissions" collection
 * 
 * @package    gui
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsersGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_group');
        $this->hasColumn('gid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('groupname', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('info', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UsersGroups', array(
             'local' => 'gid',
             'foreign' => 'gid'));

        $this->hasMany('UsersPasswd', array(
             'local' => 'gid',
             'foreign' => 'gid'));

        $this->hasMany('UsersPermissions', array(
             'local' => 'gid',
             'foreign' => 'gid'));
    }
}