<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PermissionType', 'doctrine');

/**
 * BasePermissionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $permission_type_id
 * @property string $permission
 * 
 * @method integer        getPermissionTypeId()   Returns the current record's "permission_type_id" value
 * @method string         getPermission()         Returns the current record's "permission" value
 * @method PermissionType setPermissionTypeId()   Sets the current record's "permission_type_id" value
 * @method PermissionType setPermission()         Sets the current record's "permission" value
 * 
 * @package    gui
 * @subpackage model
 * @author     Artem Yankovskiy <admin@neverdark.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePermissionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('permission_type');
        $this->hasColumn('permission_type_id', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('permission', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}