<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ObjectType', 'doctrine');

/**
 * BaseObjectType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $object_type
 * @property Doctrine_Collection $Objects
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getObjectType()  Returns the current record's "object_type" value
 * @method Doctrine_Collection getObjects()     Returns the current record's "Objects" collection
 * @method ObjectType          setId()          Sets the current record's "id" value
 * @method ObjectType          setObjectType()  Sets the current record's "object_type" value
 * @method ObjectType          setObjects()     Sets the current record's "Objects" collection
 * 
 * @package    gui
 * @subpackage model
 * @author     Artem Yankovskiy <admin@neverdark.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjectType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('object_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Objects', array(
             'local' => 'id',
             'foreign' => 'object_type_id'));
    }
}