<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NetworkType', 'doctrine');

/**
 * BaseNetworkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $network_type_id
 * @property string $network_type
 * @property string $description
 * @property Doctrine_Collection $Counters
 * 
 * @method integer             getNetworkTypeId()   Returns the current record's "network_type_id" value
 * @method string              getNetworkType()     Returns the current record's "network_type" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getCounters()        Returns the current record's "Counters" collection
 * @method NetworkType         setNetworkTypeId()   Sets the current record's "network_type_id" value
 * @method NetworkType         setNetworkType()     Sets the current record's "network_type" value
 * @method NetworkType         setDescription()     Sets the current record's "description" value
 * @method NetworkType         setCounters()        Sets the current record's "Counters" collection
 * 
 * @package    gui
 * @subpackage model
 * @author     Artem Yankovskiy <admin@neverdark.ru>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNetworkType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('network_type');
        $this->hasColumn('network_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('network_type', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Counters', array(
             'local' => 'network_type_id',
             'foreign' => 'network_type_id'));
    }
}